### ISSUE TITLE
Failure to add extension

### ISSUE THREAD

**Issue by crabsgit** [rafaelgandi/arc-tab-stash#1]
Extension does not add to Arc as of 12:25 PM 02/26/2023

**Comment by rafaelgandi** [comment]
Sorry about that.I can't seem to replicate your issue. Have you updated to the latest version of Arc?

**Comment by crabsgit** [comment]
Yes I have. I can run a reboots and I will forward you a screen grab if the
issue repeats yourself. I just wanted to inform you in case you’ve seen it
before.

**Comment by crabsgit** [comment]
Itself *

**Comment by crabsgit** [comment]
https://www.dropbox.com/s/r6wh7uv7uyrari1/Screen%20Shot%202023-02-26%20at%205.45.14%20PM.mov?dl=0

**Comment by crabsgit** [comment]
post reboot

**Comment by crabsgit** [comment]
DynamicDNS is turned off and so is uBlock

**Comment by rafaelgandi** [comment]
Thanks for letting me know man, really appreciate it. I still can't replicate it on my end but upon checking your screen share, looks like its an issue from the chrome web store. Might need to report this with the Arc team
