### ISSUE TITLE
Extensions Sync?

### ISSUE THREAD

**Issue by macwilk** [rafaelgandi/arc-tab-stash#2]
Any interest in syncing extensions on top of Favorites? This is currently a massive painpoint for me and would solve my final lasting Arc-based woe :(

**Comment by rafaelgandi** [comment]
hi @macwilk ... can you elaborate more on this?

**Comment by macwilk** [comment]
> hi @macwilk ... can you elaborate more on this?

Hey! So right now this sync's favorites between my different computers which is great and I love it! It uses my github account too which I log into on every computer so its even more perfect. This is the current scope of the project and it solves one of two of my biggest issues with Arc.

My second biggest issue is my inability to sync the actual browser extensions between my computers. This is especially becoming a huge issue to me with Windows release, meaning my previous tactic of copying the actual extensions in their folder and dropping them in other spaces / to other macbooks no longer works :(

While this request is 100% out of scope of the current project, I think given the current infrastructure that you've built out, it'd fit perfectly in as another major feature for this extension.

**Comment by rafaelgandi** [comment]
hi @macwilk ... thanks so much for using Stash. I'm glad its useful to you. With regards to syncing extensions. Have you checked out [Extension Sync](https://chromewebstore.google.com/detail/extension-sync/kimbiihomiiklblgkdllffbakadjgako)? I have not personally used it but it does seem to address your issue with syncing extensions? Plus it also uses Github gists like Stash.

**Comment by macwilk** [comment]
Hilariously I have, it works pretty well at syncing the extensions but it has some drawbacks that make it almost unusable:
- requires you to manually install each one as you sync them and if you have multiple computers with multiple spaces you'll see how sad this makes me.
- doesn't automatically sync and resync as things change. You need to manually invoke it every time you want to make things "portable" 
- it doesn't have a context of spaces so I need multiple GitHub accounts for each space 

I emailed the dev too asking for the source code so I could tweak it but haven't heard back either haha

**Comment by rafaelgandi** [comment]
> it doesn't have a context of spaces so I need multiple GitHub accounts for each space

Yikes, got it.. seems to be a pain to use then in the context of using Arc as it does not have a concept of spaces with profiles which is one of the main benefits of using Arc.

I'll definitely look into it, hopefully the developer can share his/her code to give us some sort of starting point hehehe. This seems to be a real pain point using multiple browsers. If I am going to build something similar I'll probably build it separate from Stash as I think it addresses a different concern. Thanks for sharing info about this 😁
